# Generated by Django 2.2.7 on 2019-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='subway',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
